name: mansi_server
description: A new Dart Frog application
version: 1.0.36+37

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  dart_frog_request_logger: ^0.0.2
  http: ^1.2.2
  uuid: ^4.5.0

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
